name: code build and review
on: push
env:
  imagename: "myjavaapp"
jobs:
  CICDjob:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the current repository on runner
      uses: actions/checkout@v4
    - name: Setup with Java17 and maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Build with maven
      run: mvn package
    - name: Install docker
      uses: docker/setup-docker-action@v4
    - name: Login to Docker Hub   
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.imagename }}:latest
  Deployjob:
    needs: CICDjob
    runs-on: self-hosted
    steps:
    - name: Deploy the image
      run: |
        docker run -itd -P ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.imagename }}:latest
        docker ps -a
